### ISSUE TITLE
"rch_200.rda" has magic number "version" error.

### ISSUE THREAD

**Issue by mackerman44** [KevinSee/QRFcapacity#3]
I tried installing QRFcapacity.

```
devtools::install_github("KevinSee/QRFcapacity")
```
and received the following error:
```
* installing *source* package 'QRFcapacity' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
Warning: file 'rch_200.rda' has magic number 'versi'
  Use of save versions prior to 2 is deprecated
Error in load(zfile, envir = tmp_env) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
ERROR: lazydata failed for package 'QRFcapacity'
* removing 'C:/Users/mikea/Documents/R/win-library/4.0/QRFcapacity'
```
My initial guess, without digging further at the moment, is that rch_200.rda was saved with R v3.6.x and we're now using R v4.0.x. More to come...

**Comment by KevinSee** [comment]
Yup, turns out version 2 was the default format from R 1.4.0 to 3.5.3. Version 3 became the default from R 3.6.0 and can only be read by R versions 3.5.0 and higher.

I re-saved rch_200 as version 3, but we may have to do the same with other datasets as well.

**Comment by mackerman44** [comment]
If I run into an issue w the other datasets, will it simply be a matter of
cloning the repo, load() and save() each, and then try re-installing from
github?

**Comment by KevinSee** [comment]
yes, I think so. load() the data, then use:

> usethis::use_data(rch_200,
>          version = 3,
>          overwrite = T)
>
